### PR TITLE
Fixed issue 164

### LINKED ISSUE #164: **Button Enablement Issue in ORCA Log Extraction**
### **Describe the Bug**  
When selecting the **First** or **Last** option in the **"Enter how you want the lines specified"** dropdown without entering the line number, the buttons are getting enabled. However, the buttons should only be enabled after filling in all the required fields in the text boxes.  

### **To Reproduce**  
1. Go to the **ORCA Log Extraction** tab.  
2. Upload any file and enter a search term.  
3. Select **First** or **Last** as the option and enter the number of sections.  
4. Observe that the buttons are enabled **without entering the line number**.  

### **Expected Behavior**  
- The buttons should only be enabled **after selecting all required options and entering all necessary fields**.  
- Even after entering the line number, the buttons should be enabled only when all other required inputs are filled.  

### **Screenshots**  
Image  

### **Additional Context**  
Refer to **Issue #150** for more details.

### PR DESCRIPTION
**Pull request by haneenalsewari**
Fixes #164 

**What was changed?**

This change applies to the OrcaDashboardComponent.js file in the React front end. Specifically, it modifies how the “Submit Search Query,” “Preview,” and “Download” buttons are enabled or disabled.

**Why was it changed?**

Users were able to enable the buttons after choosing “FIRST” or “LAST” in the “Enter how you want the lines specified” dropdown, even if they did not provide a line number. This caused confusion and errors when attempting to preview or download without a valid line number.

**How was it changed?**

- Added a simple check in the existing isSearchQueryEnabled() function and the isDisabled constant to verify whether the user has provided a line number when “FIRST” or “LAST” is selected.
- If the user does not supply a line number, the buttons remain disabled.

**Screenshots that show the changes (if applicable):**
image

### CODE REVIEW

File: client-app/src/components/OrcaDashboardComponent.js [hunk 1]
```diff
@@ -39,7 +39,10 @@ const OrcaDashboardComponent = () => {
   };
 
   const isSearchQueryEnabled = () => {
-    return !isUploadedFilesEmpty && searchTerms.length && specifyLines.length && sections.length;
+    const line = specifyLines[0] || {};
+    const lineNumberRequired = line.value === "FIRST" || line.value === "LAST";
```
Comment (bhumulanandinireddy) [inline client-app/src/components/OrcaDashboardComponent.js:43]: good logic usage but try  to reduce declaring  more const terms and writing in a function and call it

File: client-app/src/components/OrcaDashboardComponent.js [hunk 2]
```diff
@@ -247,12 +250,16 @@ const OrcaDashboardComponent = () => {
     setSameCriteria(false);
   };
 
+  const line = specifyLines[0] || {};
+  const lineNumberRequired = line.value === "FIRST" || line.value === "LAST";
```
Comment (bhumulanandinireddy) [inline client-app/src/components/OrcaDashboardComponent.js:254]: So that you can reduce the repeated code

**Review by bhumulanandinireddy — APPROVED** [review]
Good work done ! try to reduce declaring more const terms and writing in a function and call it so that you can get rid of repeated code

File: client-app/src/components/OrcaDashboardComponent.js (hunk 1 above)
Comment (paulongkiko) [reply client-app/src/components/OrcaDashboardComponent.js:43]: Nice way to separate that situation from the others

File: client-app/src/components/OrcaDashboardComponent.js (hunk 2 above)
Comment (paulongkiko) [reply client-app/src/components/OrcaDashboardComponent.js:254]: Agree here that repeated code could have been separated out.

File: client-app/src/components/OrcaDashboardComponent.js [hunk 3]
```diff
@@ -247,12 +250,16 @@ const OrcaDashboardComponent = () => {
...
+  const isLineNumberMissing = lineNumberRequired && (!line.lineNumber || line.lineNumber.trim() === "");
```
Comment (paulongkiko) [inline client-app/src/components/OrcaDashboardComponent.js:255]: Love this way of accounting for handling different submission types in the line number field
