### PR TITLE
File path handling in search query input on /temp route Fixes (#62)

### LINKED ISSUE #62: Fix file path handling in search query input on /temp route
**Describe the bug**
Currently, the UI improvement is in progress, and on uploading a file through the UI in /temp route, the system incorrectly interprets the file name as the input instead of the full file path. The system should use the full file path as the input.

**To Reproduce**
1. Run the application and navigate to https://localhost:3000/temp
2. Choose the ORCA log file as the input and upload it.
3. Provide the following search inputs:
  - Search term (e.g., "CARTESIAN COORDINATES (A.U.)") and click on 'Enter'
  - Lines specified (e.g., FIRST 5)
  - Number of sections (e.g., 1, 2)
4. Click on F12 and open the developer tools
5. Navigate to the Network tab in the developer tools
6. Click on Download Output in the UI
7. In the Network tab, click on find-sections and navigate to the Payload tab. Check the file path in the Request Payload. 
8. Open a new browser tab, navigate to https://localhost:3000, and repeat the above steps from 2-7 with the same inputs.
9. Observe the difference in the file_path parameter value.

**Expected behavior**
On /temp, the system should use the full file path (e.g., file_path : "/python-docker/instance/uploads/Styrene-H.txt") instead of just the file name (e.g., file_path :  "Styrene-H.txt")

**Screenshots**
https://localhost:3000/temp output:
image

https://localhost:3000/ output:
image

**Additional Context**

Please look into **setFileName** and the **fileName** values in the **DraftOrcaDashboard.js** file. In the two functions below, the file name is extracted, and the path information is discarded.

In the onFileSelected function:
`setFileName(selectedFile.name.split('/').pop());`

In the onUpload function:
```
uploadedFileName = response.data.filename.split('/').pop();
setFileName(uploadedFileName);
```
Instead of using just the file name, we need to store and use the full file path

### PR DESCRIPTION
**Pull request by mkalal6**
Fixes #62

**What was changed?**

*The changes were made in the file upload within the DraftOrcaDashboard component. Specifically, the onUpload and onSubmit functions were modified to capture and use the full file path for uploaded files rather than just the file name. Adjustments were also made to ensure that the specify_lines parameter is correctly formatted for the request payload.*

**Why was it changed?**

*This update was intended to address an issue where the system was incorrectly using only the file name instead of the full file path, causing discrepancies in file handling between routes. By ensuring the full file path is stored and used, this change aims to improve consistency and accuracy in file handling, especially in cases where the file path is essential for backend processing.*

**How was it changed?**

*onFileSelected: Modified this function to set fileName with the full file path and ensured it was compatible with windows.*

*onUpload: Updated onUpload to set fileName to the full path returned by the backend (response.data.filename). This change allows fileName to store the full path, which is required in the payload.*

*onSubmit: Updated the onSubmit function to use fileName (now containing the full file path) in the file_path field of the request payload.*

### CODE REVIEW

File: client-app/src/components/DraftOrcaDashboard.js [hunk 1]
```diff
@@ -24,7 +24,7 @@ const DraftOrcaDashboard = () => {
       return;
     }
     setSelectedFile(selectedFile);
-    setFileName(selectedFile.path);
+    setFileName(selectedFile.name.split("/").pop());
```
Comment (mkalal6) [inline client-app/src/components/DraftOrcaDashboard.js:27]: make sure that this can work on windows as well mac

File: client-app/src/components/DraftOrcaDashboard.js [hunk 2]
```diff
@@ -76,8 +76,8 @@ const DraftOrcaDashboard = () => {
     axios
       .post("http://localhost:5001/upload", formData)
       .then((response) => {
-        //const uploadedFileName = response.data.filename.split("/").pop();
-        setFileName(response.data.file_path);
+        const uploadedFileName = response.data.filename.split("/").pop();
```
Comment (mkalal6) [inline client-app/src/components/DraftOrcaDashboard.js:79]: make sure that this can work on windows as well mac

File: server/ven/bin/Activate.ps1 [hunk 3]
```diff
@@ -0,0 +1,247 @@
+<#
```
Comment (mkalal6) [inline server/ven/bin/Activate.ps1:1]: should not have committed the other files, just the DraftOrcaDashboard

**Review by mkalal6 — COMMENTED** [review]
Should have only committed the DraftOrcaDashboard file. Good completion of the issue but can make sure that two of the lines are also compatible with windows.

File: server/ven/bin/pytest
Comment (Lyskawa-Aonyx) [inline server/ven/bin/pytest:1]: Make sure to remove the comments, specifically "#!/Users/medhani/Capstone/esp/server/ven/bin/python3.11"!

File: server/ven/bin/Activate.ps1
Comment (Lyskawa-Aonyx) [inline server/ven/bin/Activate.ps1:1]: The code here is very good!

File: server/ven/pyvenv.cfg
Comment (Lyskawa-Aonyx) [inline server/ven/pyvenv.cfg:1]: Will this work on other user's machines? Do we need to check for the user's python version?

File: client-app/src/components/DraftOrcaDashboard.js [hunk 4]
```diff
@@ -24,7 +24,7 @@ const DraftOrcaDashboard = () => {
       return;
     }
     setSelectedFile(selectedFile);
-    setFileName(selectedFile.name.split("/").pop());
+    setFileName(selectedFile.name.split(/[/\\]/).pop());
```
Comment (SiriChandanaGarimella) [inline client-app/src/components/DraftOrcaDashboard.js:27]: Please remove this line as it is not needed.

File: client-app/src/components/DraftOrcaDashboard.js [hunk 5]
```diff
@@ -76,8 +76,8 @@ const DraftOrcaDashboard = () => {
     axios
       .post("http://localhost:5001/upload", formData)
       .then((response) => {
-        const uploadedFileName = response.data.filename.split("/").pop();
-        setFileName(uploadedFileName);
+        const uploadedFileName = response.data.filename.split(/[/\\]/).pop();
```
Comment (SiriChandanaGarimella) [inline client-app/src/components/DraftOrcaDashboard.js:79]: Please use 'response.data.file_name' to get the filename and assign it to uploadedFileName variable.

File: client-app/src/components/DraftOrcaDashboard.js [hunk 6]
```diff
@@ -76,8 +76,8 @@ const DraftOrcaDashboard = () => {
...
+        setFileName(response.data.filename);
```
Comment (SiriChandanaGarimella) [inline client-app/src/components/DraftOrcaDashboard.js:80]: Please use 'response.data.file_path' to get the file path and assign it to the variable setFileName. If possible, update the variable names setFileName to setFilePath and fileName to filePath throughout the file.

**Review by SiriChandanaGarimella — COMMENTED** [review]
@mkalal6 - Great work! As discussed, I updated the /upload API response to provide file_name and file_path. Here’s the updated sample response:
```
{
    "message": "Success",
    "file_name": "Styrene-H.txt",
    "file_path": "/Users/.../esp/server/instance/uploads/Styrene-H.txt"
}
```
Added the inline comments wherever it is necessary to update the code. Please review and update accordingly.

**Review by SiriChandanaGarimella — APPROVED** [review]
lgtm;

**Comment by SiriChandanaGarimella** [comment]
This fixes the issue #73 as well
