### PR TITLE
Fixed Issue 93

### LINKED ISSUE #93: BUG: Fix Specify Lines value in search query input on /temp route
**Describe the bug**
Currently, the UI improvement is in progress, and on providing the Specify Lines value through the UI in /temp route, the system incorrectly interprets the value as [object Object] instead of the provided value. The system should display the chosen value of the dropdown followed by the specified line value if applicable.

**To Reproduce**

1. Run the application and navigate to https://localhost:3000/temp
2. Choose the ORCA log file as the input and upload it.
3. Provide the following search inputs:
      - Search term (e.g., "CARTESIAN COORDINATES (A.U.)") and click on 'Enter'
      - Lines specified (e.g., FIRST 5)
      - Number of sections (e.g., 1, 2)
7. Click on F12 and open the developer tools
8. Navigate to the Network tab in the developer tools
9. Click on Download Output in the UI
10. In the Network tab, click on find-sections and navigate to the Payload tab. Check the specify_lines value in the Request Payload.
11. Open a new browser tab, navigate to https://localhost:3000/, and repeat the above steps from 2 to 7 with the same inputs.
12. Observe the difference in the specify_lines parameter value.

**Expected behavior**
On /temp, the system should display "FIRST 5" instead of [object Object] if "First" is selected in the dropdown and the "lines specified" value is 5, and if "Whole" is selected in the dropdown, then "WHOLE" should be displayed in the specify_lines.

**Screenshots**
https://localhost:3000/temp output:
image

https://localhost:3000/ output:
image

**Additional context**
Make use of specifyLines[0].showInput, specifyLines[0].lineNumber, specifyLines[0].value in the DraftOrcaDashboard.js file to get the required values.

### PR DESCRIPTION
**Pull request by Lyskawa-Aonyx**
Fixes #93 

**What was changed?**
-Many lines in the DraftOrcaDashboard.js file were changed to fix the issue. 

*Here, describe what part of the application you changed (e.g. login page, database, etc.). If possible, mention what specific components were added, removed, or modified.*
-The way the program passes a payload from the front end to the backend was changed. 

**Why was it changed?**
-There was an error in the payload that was being passed to the backend that needed to be fixed to properly work. 
-Currently, the UI improvement is in progress, and on providing the Specify Lines value through the UI in /temp route, the system incorrectly interprets the value as [object Object] instead of the provided value. The system should display the chosen value of the dropdown followed by the specified line value if applicable.

**How was it changed?**
-I changed the specify_lines: specifyLines function to work properly with added functionality.
-I also changed setSpecifyLines([{ value, showInput: value === "FIRST" || value === "LAST", lineNumber: "" }]); to add the lineNumber section.

*Here, get into detail about what files you modified, and talk about the most important lines in regards to fixing the issue.*
-The only file I changed was DraftOrcaDashboard.js

### CODE REVIEW

File: client-app/src/components/DraftOrcaDashboard.js [hunk 1]
```diff
@@ -101,8 +102,19 @@ const DraftOrcaDashboard = () => {
       file_path: filePath.toString(),
       search_terms: searchTerms,
       sections: sections,
-      specify_lines: specifyLines.join(","),
+      specify_lines: specifyLines
```
Comment (SiriChandanaGarimella) [inline client-app/src/components/DraftOrcaDashboard.js:105]: Can you please simplify the code? This looks a bit complex and difficult to maintain. Please implement the following changes:

- Add a function for the formatting part
- Move the formatting logic to formatSpecifyLines()
- Call the method in specify_lines parameter as: specify_lines: formatSpecifyLines()

File: client-app/src/components/DraftOrcaDashboard.js [hunk 2]
```diff
@@ -51,15 +52,15 @@ const DraftOrcaDashboard = () => {
...
-            type="text"
-            className="form-control"
-            placeholder="Enter line number"
-            value={line.lineNumber || ""}
-            onChange={(e) => {
-              const updatedLines = [{ ...line, lineNumber: e.target.value }];
-              setSpecifyLines(updatedLines);
-            }}
-          />
+          type="text"
```
Comment (SiriChandanaGarimella) [inline client-app/src/components/DraftOrcaDashboard.js:55]: Please restore the original code indentation and undo the current changes.

**Review by SiriChandanaGarimella — CHANGES_REQUESTED** [review]
@Lyskawa-Aonyx - Great effort! I have added some inline review comments. Can you please look into them. Also, please add the change to the specify_lines parameter in the  [fetchDocumentPreview()](https://github.com/oss-slu/esp/pull/112/files#diff-da03ff21942536e89ff544a186a8114d1550ef9f85f0f067f561a68bb4d7448bR189) as well

**Review by SiriChandanaGarimella — APPROVED** [review]
Pushed the required changes. lgtm;
